from pathlib import Path
import json,html,zipfile
P=Path(__file__).resolve().parents[1];E=html.escape
texts={
'pt':['pt-BR','Controle de tokens, na prática.','Entenda o consumo. Escolha os recursos. Confira o resultado.','Ler os 22 tópicos','Baixar kit','Guia de uso','Prévia visual aprovada','132 segundos · 22 cenas · sem narração. Os vídeos finais com avatar e voz do Nei em português, espanhol e inglês estão em produção.','Calculadora da API','Entrada total','Entrada em cache','Escrita de cache','Saída faturável','Calcular','Simulação com tarifas de 20/09/2026. Não representa o limite da sua assinatura. Inclua raciocínio faturável na saída. Ferramentas e outros adicionais não estão incluídos.','Use em uma tarefa real','1. Obtenha os materiais','Python 3 é necessário apenas para a calculadora local. O guia e os prompts funcionam no navegador.','2. Instale a skill, se desejar','Copie a pasta economia-tokens para ~/.codex/skills/. Revise uma instalação existente antes de substituí-la. Abra uma nova sessão do Codex.','3. Execute e compare','Mude uma variável por vez, preserve o critério de qualidade e compare tarefas equivalentes.','Aula completa','Abra cada tópico para ler a explicação completa.','Fontes e correções','Materiais disponíveis','Roteiro completo','Os prompts são autorais INEMA. A skill orienta o trabalho; não aumenta limites nem altera a cobrança.','Tema','Total estimado','Valores inválidos: use inteiros não negativos e cache total menor ou igual à entrada.','Faixa de contexto longo aplicada à solicitação inteira.','Tarifa padrão.','Prompts práticos'],
'es':['es','Control de tokens, en la práctica.','Comprende el consumo. Elige los recursos. Comprueba el resultado.','Leer los 22 temas','Descargar kit','Guía de uso','Vista previa visual aprobada','132 segundos · 22 escenas · sin narración. Los videos finales con el avatar y la voz de Nei en portugués, español e inglés están en producción.','Calculadora de la API','Entrada total','Entrada en caché','Escritura de caché','Salida facturable','Calcular','Simulación con tarifas del 20/09/2026. No representa el límite de tu suscripción. Incluye el razonamiento facturable en la salida. No incluye herramientas ni otros cargos adicionales.','Úsalo en una tarea real','1. Obtén los materiales','Solo necesitas Python 3 para la calculadora local. La guía y los prompts funcionan en el navegador.','2. Instala la skill, si lo deseas','Copia la carpeta economia-tokens a ~/.codex/skills/. Revisa cualquier instalación existente antes de sustituirla. Abre una nueva sesión de Codex.','3. Ejecuta y compara','Cambia una variable a la vez, conserva el criterio de calidad y compara tareas equivalentes.','Lección completa','Abre cada tema para leer la explicación completa.','Fuentes y correcciones','Materiales disponibles','Guion completo','Los prompts son originales de INEMA. La skill orienta el trabajo; no aumenta límites ni modifica la facturación.','Tema','Total estimado','Valores inválidos: usa enteros no negativos y una caché total menor o igual que la entrada.','Tarifa de contexto largo aplicada a toda la solicitud.','Tarifa estándar.','Prompts prácticos'],
'en':['en','Token control, in practice.','Understand usage. Choose your tools. Check the result.','Read all 22 topics','Download kit','User guide','Approved visual preview','132 seconds · 22 scenes · no narration. The final videos with Nei’s avatar and voice in Portuguese, Spanish and English are in production.','API calculator','Total input','Cached input','Cache writes','Billable output','Calculate','Simulation using rates checked on September 20, 2026. This does not represent your subscription allowance. Include billable reasoning in output. Tools and other charges are excluded.','Use it on a real task','1. Get the materials','Python 3 is required only for the local calculator. The guide and prompts work in your browser.','2. Install the skill, if desired','Copy the economia-tokens folder into ~/.codex/skills/. Review an existing installation before replacing it. Open a new Codex session.','3. Run and compare','Change one variable at a time, keep the quality criterion and compare equivalent tasks.','Complete lesson','Open each topic to read the full explanation.','Sources and corrections','Available materials','Complete script','These prompts were written by INEMA. The skill guides your work; it does not increase allowances or change billing.','Theme','Estimated total','Invalid values: use nonnegative integers and total cache no greater than input.','Long-context rates applied to the entire request.','Standard rates.','Practical prompts']}
prompts={
'pt':['Identifique se estamos usando ChatGPT, Codex ou API. Use somente indicadores de consumo realmente disponíveis. Separe dados observados, estimativas e informações indisponíveis. Não invente saldo ou renovação. Aponte duas fontes prováveis de desperdício e uma mudança por vez. Não altere configurações sem autorização.','Objetivo: [resultado]. Escopo: [arquivos]. Conclusão: [evidência]. Leia instruções aplicáveis. Faça buscas delimitadas. Preserve logs grandes em arquivo e mostre erros e resumo. Use subagentes somente se autorizados e úteis. Execute e verifique o resultado.','Prepare uma passagem concisa com objetivo, decisões aprovadas, estado atual, arquivos relevantes, verificações, pendências e próximo passo. Não copie histórico inteiro nem segredos. Preserve restrições e diferencie concluído de planejado. Não apague nem compacte automaticamente.'],
'es':['Identifica si usamos ChatGPT, Codex o API. Usa solo indicadores de consumo realmente disponibles. Separa datos observados, estimaciones e información no disponible. No inventes saldo ni renovación. Señala dos posibles fuentes de desperdicio y un cambio a la vez. No modifiques ajustes sin autorización.','Objetivo: [resultado]. Alcance: [archivos]. Finalización: [evidencia]. Lee las instrucciones aplicables. Haz búsquedas acotadas. Guarda registros grandes en archivos y muestra errores y un resumen. Usa subagentes solo si están autorizados y son útiles. Ejecuta y verifica el resultado.','Prepara un traspaso conciso con objetivo, decisiones aprobadas, estado actual, archivos relevantes, verificaciones, pendientes y siguiente paso. No copies todo el historial ni secretos. Conserva las restricciones y distingue lo terminado de lo planeado. No borres ni compactes automáticamente.'],
'en':['Identify whether we are using ChatGPT, Codex or the API. Use only usage indicators that are actually available. Separate observed data, estimates and unavailable information. Do not invent balances or reset times. Identify two likely sources of waste and one change at a time. Do not change settings without authorization.','Goal: [result]. Scope: [files]. Completion: [evidence]. Read applicable instructions. Use bounded searches. Save large logs to files and report errors and a useful summary. Use subagents only when authorized and useful. Execute and verify the result.','Prepare a concise handoff with the goal, approved decisions, current state, relevant files, checks, pending work and next step. Do not copy the entire history or secrets. Preserve constraints and distinguish completed from planned work. Do not delete or compact automatically.']}
css=(P/'scripts/guide-style.css').read_text()+'''\n:root{--amb-text:var(--amb)}body.light{--amb-text:#965b10}a,.amb,.chip,nav .brand,.flow .arr,.phase .tag,.num,.lesson-note{color:var(--amb-text)}body.light nav{background:var(--bg)}nav .wrap{gap:12px}nav .links{gap:10px}.languages{display:flex;gap:18px;padding:16px 0}.languages a[aria-current]{text-decoration:underline;text-underline-offset:6px}video{width:100%;max-height:650px;background:var(--bg2);border-radius:14px}details{border-bottom:1px solid var(--line);padding:22px 0}summary{cursor:pointer;font-family:Sora;font-size:1.12rem}details p{max-width:78ch}.lesson-note{color:var(--amb-text)}label{display:block}input{display:block;width:100%;padding:12px;margin:7px 0 18px;background:var(--bg2);color:var(--txt);border:1px solid var(--line);border-radius:8px;font:inherit}button{cursor:pointer;border:0;font:inherit}output{display:block;margin-top:20px;font-size:1.25rem}.step>div{min-width:0}pre{white-space:pre-wrap;overflow-wrap:anywhere}.prompt{line-height:1.7}section{scroll-margin-top:70px}:focus-visible{outline:3px solid var(--sky);outline-offset:4px}@media(max-width:620px){nav .wrap{height:auto;min-height:60px;flex-wrap:wrap;gap:8px;padding:10px 16px}nav .brand{font-size:.9rem}nav .links{gap:8px}.links .btn{font-size:.7rem}.hero .wrap{gap:25px}.hero p.lead{max-width:none}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}'''
delivery_path=P/'docs/video-delivery.json'
delivery=json.loads(delivery_path.read_text()) if delivery_path.exists() else {}
for lang,t in texts.items():
 d=json.loads((P/f'docs/lesson-{lang}.json').read_text());base='.' if lang=='pt' else '..';root='..' if lang=='pt' else '../..';out=P/'guia'/('' if lang=='pt' else lang);out.mkdir(parents=True,exist_ok=True)
 links=''.join(f'<a href="{base}/{"" if c=="pt" else c+"/"}" '+('aria-current="page"' if c==lang else '')+f'>{label}</a>' for c,label in [('pt','Português'),('es','Español'),('en','English')])
 chapters=''.join(f'<details><summary>{i+1:02d} · {E(s["title"])}</summary><p class="chip">{E(s["chapter"])}</p><p>{E(s["speech"])}</p><p class="lesson-note">{E(s["takeaway"])}</p></details>' for i,s in enumerate(d))
 ps=''.join(f'<div class="step"><div class="b">{i+1}</div><div><pre class="prompt">{E(s)}</pre></div></div>' for i,s in enumerate(prompts[lang]))
 form=''.join(f'<label>{E(t[9+i])}<input name="{n}" type="number" min="0" step="1" value="{v}" required></label>' for i,(n,v) in enumerate([('input',100000),('cached',90000),('written',0),('output',2000)]))
 video_src=f'{root}/video/previa-visual-pt.mp4';video_extra='';video_meta='PT-BR · 1920 × 1080 · 24 fps';version='1.0.0'
 if lang in delivery:
  item=delivery[lang];video_src=item['url'];version='1.1.0'
  t[6]={'pt':'Aula completa com Nei','es':'Lección completa con Nei','en':'Full lesson with Nei'}[lang]
  t[7]={'pt':'22 tópicos ilustrados, com narração e legendas em português.','es':'22 temas ilustrados, con narración y subtítulos en español.','en':'22 illustrated topics, with English narration and subtitles.'}[lang]
  video_meta=f"{lang.upper()} · {int(item['duration']//60)}:{int(item['duration']%60):02d} · 1920 × 1080 · 25 fps"
  download={'pt':'Baixar vídeo','es':'Descargar video','en':'Download video'}[lang];subtitle={'pt':'Legendas SRT','es':'Subtítulos SRT','en':'SRT subtitles'}[lang]
  video_extra=f'<p><a href="{E(video_src)}">{download}</a> · <a href="{E(item["srt"])}">{subtitle}</a></p>'
 page=f'''<!doctype html><!-- THESIS: Teach token control with readable complete lessons and a transparent calculator within the pinned INEMA template. FINISH: Keep source caveats, verify three languages and mobile, maintain accessible light/dark contrast; label silent preview and pending narrated videos truthfully. --><html lang="{t[0]}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Astra Básico — {t[1]}</title><meta name="description" content="{t[2]}"><link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;600;800&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet"><style>{css}</style></head><body>
<nav><div class="wrap"><a class="brand" href="#top">◈ Astra Básico</a><span class="sep">|</span><span class="clubpro"><a class="inema" href="https://inema.club" target="_blank" rel="noopener">INEMA.CLUB</a><span class="sep">-</span><a class="pro" href="https://inema.pro" target="_blank" rel="noopener">PRO</a></span><div class="links"><a class="sec" href="#guia">{t[5]}</a><button class="tgl" id="themeToggle" aria-label="{t[28]}">☀</button><a class="btn" href="https://github.com/inematds/astrabasico">GitHub</a></div></div></nav>
<header class="hero" id="top"><div class="glow"></div><div class="wrap"><div><div class="languages">{links}</div><span class="chip">INEMA · GPT-6 ASTRA</span><h1>{t[1]}</h1><p class="lead">{t[2]}</p><div class="cta"><a class="btn" href="#aula">{t[3]}</a><a class="btn ghost" href="{root}/kit-economia-tokens.zip" download>{t[4]}</a></div></div><figure><img src="{base}/assets/hero.png" alt="AI · tokens · INEMA" width="1024" height="768"></figure></div></header>
<section id="video"><div class="wrap"><span class="chip">01 · VIDEO</span><h2>{t[6]}</h2><p class="sub">{t[7]}</p><video controls preload="metadata" poster="{base}/assets/hero.png" aria-label="{t[6]}"><source src="{E(video_src)}" type="video/mp4"></video><p class="mut">{video_meta}</p>{video_extra}</div></section>
<section id="guia"><div class="wrap"><span class="chip">02 · KIT</span><h2>{t[15]}</h2><p class="sub">{t[27]}</p><div class="step"><div class="b">1</div><div><h3>{t[16]}</h3><p>{t[17]}</p><pre>git clone https://github.com/inematds/astrabasico.git\ncd astrabasico</pre></div></div><div class="step"><div class="b">2</div><div><h3>{t[18]}</h3><p>{t[19]}</p><pre>$economia-tokens</pre></div></div><div class="step"><div class="b">3</div><div><h3>{t[20]}</h3><p>{t[21]}</p><pre>python3 kit/economia-tokens/scripts/estimar.py --input 100000 --cached 90000 --output 2000</pre></div></div></div></section>
<section id="calc"><div class="wrap"><span class="chip">03 · API STANDARD · USD</span><h2>{t[8]}</h2><p class="sub">{t[14]}</p><form id="calculator"><div class="grid g4">{form}</div><button class="btn" type="submit">{t[13]}</button><output id="result" aria-live="polite"></output></form><p class="mut">1M tokens: input $10 · cached $1 · cache write $12.50 · output $50. &gt;272,000: input/cache ×2 · output ×1.5.</p><a href="https://developers.openai.com/api/docs/models/gpt-6-astra">OpenAI · GPT-6 Astra</a></div></section>
<section id="prompts"><div class="wrap"><span class="chip">04 · PROMPTS</span><h2>{t[33]}</h2><p class="sub">INEMA · {lang.upper()}</p>{ps}</div></section>
<section id="aula"><div class="wrap"><span class="chip">05 · 22 / 22</span><h2>{t[22]}</h2><p class="sub">{t[23]}</p>{chapters}</div></section>
<section id="fontes"><div class="wrap"><h2>{t[25]}</h2><p><a href="{root}/docs/ROTEIRO-{lang.upper()}.md">{t[26]} · {lang.upper()}</a></p><p><a href="{root}/docs/FONTES-E-CORRECOES.md">{t[24]} · PT-BR</a></p><p><a href="{root}/kit-economia-tokens.zip">{t[4]}</a></p><p><a href="https://www.youtube.com/watch?v=XgMhU4CE-lQ">YouTube · Sharbel A · Source</a></p></div></section>
<footer><div class="wrap"><span class="pill">Python 3</span><span class="pill">HyperFrames</span><span class="pill">v{version}</span><p>Astra Básico · <a href="https://github.com/inematds/astrabasico">GitHub</a> · <a href="https://inema.club">INEMA.CLUB</a></p></div></footer>
<script>const labels={json.dumps(t,ensure_ascii=False)};const toggle=document.getElementById('themeToggle');if(localStorage.getItem('astrabasico-theme')==='light')document.body.classList.add('light');toggle.onclick=()=>{{const light=document.body.classList.toggle('light');localStorage.setItem('astrabasico-theme',light?'light':'dark');}};const form=document.getElementById('calculator');function calculate(e){{if(e)e.preventDefault();const n=['input','cached','written','output'].map(k=>Number(form.elements[k].value));const [i,c,w,o]=n;const result=document.getElementById('result');if(n.some(x=>!Number.isSafeInteger(x)||x<0)||c+w>i){{result.textContent=labels[30];return;}}const long=i>272000;const a=(i-c-w)*10*(long?2:1)/1e6,b=c*(long?2:1)/1e6,d=w*12.5*(long?2:1)/1e6,f=o*50*(long?1.5:1)/1e6;result.textContent=labels[29]+': US$ '+(a+b+d+f).toFixed(6)+' · '+(long?labels[31]:labels[32])+' [input '+a.toFixed(6)+' + cache '+b.toFixed(6)+' + write '+d.toFixed(6)+' + output '+f.toFixed(6)+']';}}form.addEventListener('submit',calculate);calculate();</script></body></html>'''
 (out/'index.html').write_text(page)
 (P/f'kit/PROMPTS-{lang.upper()}.md').write_text('# INEMA\n\n'+'\n\n'.join(prompts[lang]))
with zipfile.ZipFile(P/'kit-economia-tokens.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in (P/'kit').rglob('*'):
  if f.is_file():z.write(f,f.relative_to(P/'kit'))
print('3 pages, 66 scenes, multilingual prompts, kit generated')
